site_name: BlueGrid Docs

theme:
  name: material
  feature: 
    - search.suggest
    - search.highlight
    - content.tabs.link

plugins:
  - search

nav: 
  - Introduction: "index.md"
  - Tutorial:
    - Tuturial Subsection: "pages/tutorial.md"
  - About: "pages/about.md"
  - FAG: "pages/fag.md"


