site_name: BlueGrid
site_description: BlueGrid is a professional construction quantity take-off software.
site_author: BlueGrid Ltd.


theme:
  name: material
  custom_dir: overrides
  feature:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
  palette:
    #Palette toggle for light mode
    - scheme: slate
#      toggle:
##        icon:material/brightness-4
#        name:Switch to light mode
#
#    #Palette toggle for dark mode
#    - scheme: default
#      toggle:
##        icon:material/brightness-4
#        name:Switch to dark mode

  logo: assets/media/favicon.png
  favicon: assets/media/favicon.ico

plugins:
  - search
  - mkdocs-video

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
#  - pymdownx.highlight
#  - pymdownx.inlinehilite
#  - pymdownx.snippets
#  - pymdownx.superfences
extra_css:
  - assets/css/custom.css

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:bluegrid@bluegridltd.com
      name: email
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/profile.php?id=100087744853278
      name: facebook



nav:
  - Overview: 'index.md'
  - Project: 'project.md'
  - Blueprints : "pdf.md"
  - Materials:
      - Catalogs/WBS: "wbs.md"
      - Materials: "material.md"
  - Draws:
      - PDF Layers on/off: "pdf_layer.md"
      - Shape tools: "shape_tool.md"
      - Annotation tools: "annotation_tool.md"
      - Symbol tools: "symbol_tool.md"
      - Styling: "styling.md"
  - Transform and Modify: "transform.md"
  - Styles: "style.md"
  - Resources: "resource.md"
  - Release notes: "releases.md"
  - Issue Reports: "issue.md"
  - Contact: "contact.md"

