site_name: BlueGrid

theme:
  name: material
  feature:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
  palette:
#    primary: Orange
  logo: assets/media/favicon.png
  favicon: assets/media/favicon.ico

plugins:
  - search
  - mkdocs-video

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Overview: 'index.md'
  - Project:
      - Create: "create.md"
      - Open: "open_project.md"
  - PDF:
      - Import files: "import_pdf.md"
      - Remove files: "remove_pdf_file.md"
      - Remove pages: "remove_pages.md"
      - Append pages: "append_pages.md"
      - Export pages: "export_pdf.md"
      - Replace pages: "replace_page.md"

#  - Import/export pdf files: "pages/import_export_pdf.md"
#  - Materials: "pages/material.md"
#  - Quantity take-off:
#    - Setting scale: "pages/set_scale.md"
#    - Take-off tools: "pages/take_off_tools.md"
#    - Annotation tools: "pages/annotation_tools.md"
#    - Snaps:
#      - Point snap: "pages/point_snap.md"

  # - About: "pages/about.md"
  # - FAG: "pages/fag.md"


